### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by jpshelley** [RationalCoding/hls-server#4]
Any chance an example project could be included for clarity?

**Comment by RationalCoding** [comment]
Anything in particular that's not clear?

The simplest way to get started is to do `require('hls-server')(8000)` after doing `npm install hls-server`. This will make a new http server, bind the middleware and start the server on port 8000.

Any .m3u8 and .ts files in the folder /public/videos will be served on localhost:8000/streams. 

So public/videos/out.m3u8 and it's related .ts files will be available on localhost:8000/streams/out.m3u8

You need an HLS player with that as it's source. HLS.js or the video element in Safari.

**Comment by RationalCoding** [comment]
Do you want a fast command like simplehttpserver has? I can add that.

**Comment by jpshelley** [comment]
@RationalCoding Yeah that sounds like a good idea. I just started learning about Node/npm recently and not quite sure how to actually run your project yet.

**Comment by jpshelley** [comment]
I think I finally figured it out though, just needed to run `node index.js` to actually run the server.

**Comment by RationalCoding** [comment]
Oh I see. Yes, this is a module, not a standalone project, so there's no "npm start" or the like.

**Comment by RationalCoding** [comment]
You can now just install the module globally with `npm install -g hls-server` and then you'll have the command `hlsserver`. 

It'll just start a server from the current directory on port 8000.
