### ISSUE TITLE
Live HLS

### ISSUE THREAD

**Issue by Shich360** [RationalCoding/hls-server#5]
Hi,
I'm trying to create a server which boadcast in live some videos (a playlist like video01.m3u8, next video02.m3u8, video03.m3u8) like a webtv in live (note on demand) no pause...

it is possible to start/use in my development  hls-server ? it seems to play only  on demand video. (?)

thanks

**Comment by RationalCoding** [comment]
This module supports both live and on-demand video. You should be using a single .m3u8 file that is updated accordingly. (see the example on converting an RTMP stream)

**Comment by Shich360** [comment]
Thanks for your answer !
I dont have any RTMP stream, but original mp4 video files or 10 seconds segmented .ts with .m3u8 only.
I'm trying to use a single (and on the fly updated) live playlist m3u8 file with the m3u8 package. Adding item and removing the first every 10 sec... but not really efficient...

**Comment by RationalCoding** [comment]
I know that seems inefficient, but that' the spec. Generation of the m3u8 file should be relatively fast though.

If your m3u8 is being properly generated, that should work.

**Comment by Shich360** [comment]
Ok, Thanks for your help !
