### ISSUE TITLE
Server serves m3u8 as text

### ISSUE THREAD

**Issue by trufa** [RationalCoding/hls-server#6]
I'm running the sample code as is.

![Image of Yaktocat](https://i.imgur.com/4XmKQxY.pngg)

And I get on http://localhost:8000/streams/out.m3u8:

![Image of Yaktocat](https://i.imgur.com/La2TkDs.png)

I don't know how I can be of more help cause there is no other output.

I'm running node 6 lts, what I see is the actual code of the desired m3u8.

**Comment by RationalCoding** [comment]
I'm assuming you're using a browser that supports HLS natively (like Safari)?

The video will be at:
http://localhost:8000/public/videos/output

NOT:
http://localhost:8000/public/videos/output.**m3u8**

**Comment by RationalCoding** [comment]
Ignore my previous comment. That was incorrect. Safari requires the URL to be in a video element. Seeing the m3u8 as text is expected behaviour.

```html
<video src="http://localhost:8000/streams/out2.m3u8">
```

Theres a demo player at `http://localhost:8000/player.html`. You'll have to inspect the video element and change it to be your URL.

**Comment by trufa** [comment]
@RationalCoding Thanks for the quick response, I would have sworn safari run it natively.

This solved the issue partially but for some reason I only see a frozen image now, I'm a little bit at a loss as to how to debug it. 

Thanks for all the help.

**Comment by RationalCoding** [comment]
Is the image a frame from your video?

**Comment by trufa** [comment]
@RationalCoding yes!

**Comment by RationalCoding** [comment]
How are you transcoding your video? 

```javascript
var ffmpeg = require('fluent-ffmpeg')

fmpeg('input.mp4', { timeout: 432000 }).addOptions([
    '-profile:v baseline',
    '-level 3.0',
    '-s 640x360',
    '-start_number 0',
    '-hls_time 10',
    '-hls_list_size 0',
    '-f hls'
  ]).output('public/videos/output.m3u8').run()
```

**Comment by trufa** [comment]
@RationalCoding Most is solved! I had to show controls and click play! Not my best moment as a dev :)

Now I just have to make it seek the the last part and be live, I'll give it a shot. Thanks for all the quick replies you rock!
