### ISSUE TITLE
How to set Access-Control-Allow-Origin in header

### ISSUE THREAD

**Issue by trufa** [RationalCoding/hls-server#7]
I have to servers running at the same time, the hls-server is the second one and run in a different port.

I am using hls.js to make hls run in chrome, this library makes a request for the m3u8 which gives a CORS error which would be solved by adding: `Access-Control-Allow-Origin: "*"` to the header.

Would this be possible without forking the repo and modifying it, I haven't been able to pass those params to hls-server dynamically.

Thanks!

**Comment by RationalCoding** [comment]
It can be used like any http middleware:

```javascript
var httpAttach = require('http-attach') // useful module for attaching middlewares
var HLSServer = require('hls-server')
var http = require('http')

var server = http.createServer()

function middleware (req, res, next) {
    // set your headers here
    request.setHeader('Access-Control-Allow-Origin', '*');
    next()
}
httpAttach(server, middleware)

var hls = new HLSServer(server, {
  path: '/streams',     // Base URI to output HLS streams
  dir: 'public/videos'  // Directory that input files are stored
})
server.listen(8000)
```

**Comment by RationalCoding** [comment]
Note that:

```javascript
var hls = new HLSServer(server, {
  path: '/streams',     // Base URI to output HLS streams
  dir: 'public/videos'  // Directory that input files are stored
})
```

is just a convenience for:

```javascript
var hls = new HLSServer()
hls.attach(server, {
  path: '/streams',     // Base URI to output HLS streams
  dir: 'public/videos'  // Directory that input files are stored
})
```

**Comment by RationalCoding** [comment]
Does this solve your question?

**Comment by RationalCoding** [comment]
@trufa It seems you have to put the CORS middleware after this one. I've updated my answer accordingly.

**Comment by christw92** [comment]
I used the code exactly as posted above.
I'm getting 
`req.setHeader is not a function` for the line `req.setHeader('Access-Control-Allow-Origin', '*');`.
Any ideas why?

**Comment by christw92** [comment]
Ok I noticed that its not clear to me why I would like to modify the req header. I replaced req with res and CORS header is set correct now.

**Comment by RationalCoding** [comment]
Typo, sorry about that.

**Comment by kenarp** [comment]
> It can be used like any http middleware:
> 
> ```js
> var httpAttach = require('http-attach') // useful module for attaching middlewares
> var HLSServer = require('hls-server')
> var http = require('http')
> 
> var server = http.createServer()
> 
> var hls = new HLSServer(server, {
>   path: '/streams',     // Base URI to output HLS streams
>   dir: 'public/videos'  // Directory that input files are stored
> })
> 
> function yourMiddleware (req, res, next) {
>     // set your headers here
>     res.setHeader('Access-Control-Allow-Origin', '*');
>     next()
> }
> httpAttach(server, yourMiddleware)
> server.listen(8000)
> ```

Worked with the CORS problem for 2days and finally found this solution, thank you! I followed the way used in the `test/basic.js` which declares the addCors function and attaches it to the http-server, prior to initializing the HLSServer, and had no luck. But as soon as I switched the order, everything works beautifully, magic. Just want to say thank you again!
