### ISSUE TITLE
Can this package be used to accept an HLS stream from another server and then restream it out?

### ISSUE THREAD

**Issue by ryanscottaudio** [RationalCoding/hls-server#8]
I have a macOS application that creates an HLS stream; I'm trying to figure out how to stream it to a server and then use that server to restream it to an iOS app that will be installed on multiple phones. Is this possible with this package? Am I overthinking it? Thanks!

**Comment by RationalCoding** [comment]
If you mean a stream of .ts files and a *valid* .m3u8 file, then sure. Just write them to the file system and everything should work out fine. You will need to check that they have been written else the module will try and fetch files that don't exist yet. Place another middleware ahead of this one.

**Comment by RationalCoding** [comment]
This module doesn't care where the actual .ts and .m3u8 files come from, so if you download them from another server, that'll work.

**Comment by ryanscottaudio** [comment]
But I definitely have to write them to the filesystem? I'm asking because it's a live stream from the macOS app that can run indefinitely. Would I just have to write the .m3u8 file to the filesystem or the .ts files also as they come in?

Sorry, I'm very new to HLS in general.

**Comment by RationalCoding** [comment]
I suppose you could keep them in memory instead of the file system. You don't keep more than a few .ts segments (just the ones listed in the m3u8 file).

Knowing the output of the stream would help greatly.

**Comment by ryanscottaudio** [comment]
Ok, thanks!

**Comment by RationalCoding** [comment]
I thought about this a little more and realized that it might be wrong to have the filesystem built-in to this module (I think reading video from databases is way more common in production).

I've added the option to add a provider that will give streams without touching fs. It should make your usecase much easier to implement.

**Comment by ryanscottaudio** [comment]
@RationalCoding that's awesome! thanks!

**Comment by tonywagner** [comment]
This looks really awesome, but could you quickly show how you'd restream, say, the Big Buck Bunny test stream with your in-memory stream provider? https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8

**Comment by jcc10** [comment]
Could we please get a example? The only thing I need this for is taking a HLS livestream and adding CORS. And to be honest, I don't know what I'm doing with HLS, I just know I can get a repeater working.
