### ISSUE TITLE
On the fly production of streams?

### ISSUE THREAD

**Issue by maddox** [RationalCoding/hls-server#9]
Are there any options here for producing the segments and streams on the fly?

I'd like to make a request with resolution, bitrate, and video file path, and have that video transcoded/remuxed on the fly and segmented and served out.

**Comment by RationalCoding** [comment]
This module is for serving HLS streams, not generating them. Did you see the README section on producing streams with ffmpeg?

**Comment by maddox** [comment]
Yeah, I understand that. I was just wondering if there was the potential to add on the fly production to the project, or if there was something technical preventing it.

**Comment by RationalCoding** [comment]
Oh I see. You can use producers (see In-Memory streams) to provide the manifest and segment per each request.

I don’t know the FFMPEG command to just generate a single segment, but I don’t see why it wouldn’t be possible (if somewhat slow).
